### PR TITLE
Swift 2.3 Compatibility

### PR DESCRIPTION
**Pull request by gblotter**
Ran Xcode 8 Project converter, no code changes were necessary.

### CODE REVIEW

**Comment by ttuygun** [comment]
Hi @gblotter. Can I run this library in Xcode 7.3.1 with Swift 2.3? Because I have some issues with setup requirements which is some definitions in AppDelegate.swift file.
Here is my code:
```
let slideMenuController = SlideMenuController(mainViewController: EntryDetailedTableViewController, leftMenuViewController: LeftActionsViewController, rightMenuViewController: RightActionsViewController)
self.window?.rootViewController = slideMenuController
self.window?.makeKeyAndVisible()
```
When I define this way, I encountered error like this:
Missing argument label 'coder:' in call

Why this is happening? Is this project incompatible with Swift 2.3 in Xcode 7.3.1?

**Comment by gblotter** [comment]
@ttuygun Xcode 7.3.1 doesn't use Swift 2.3 out of the box.  Unless you've done special things to do download Swift source, etc. then that's outside of what I've done... But straight out of the box, Xcode 7.3.1 doesn't use/work with Swift 2.3

**Comment by ttuygun** [comment]
Sorry for information. I use Swift 2.2 but the error is the same.

**Comment by Codeido** [comment]
Hi @gblotter & @ttuygun   
The actual version works great with Swift 2.3 and Swift 3.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/a74a0a26c21a49dcd4ed0c24fb352a68f89eff33

Thanks
- Paolo

**Pull request closed without merging**
