### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by yonekawa**
Add framework scheme and target for support [Carthage](https://github.com/Carthage/Carthage)
And change project structure. sample project rename to `DemoApp`
So, we can use great SlideMenuControllerSwift library as Embedded Framework!

You can try to install by Carthage from my forked repository.

```
github "yonekawa/SlideMenuControllerSwift" "1.2.2"
```

### CODE REVIEW

**Comment by yonekawa** [comment]
Sorry I didn't check install by cocoapods.
Could you review it?

**Comment by ollieatkinson** [comment]
:+1:

**Comment by dekatotoro** [comment]
@yonekawa 
Sorry, it was slower to check.
It would help us if you would have conflict resolution in the latest master.

**Comment by dekatotoro** [comment]
Carthage Support #77 
This issue closes.

**Pull request closed without merging**
