### PR TITLE
updated for new swift version

### PR DESCRIPTION
**Pull request by alexsanderkhitev**

### CODE REVIEW

**Comment by dekatotoro** [comment]
Thank you pull request. 
Please except xcuserdata.

**Comment by alexsanderkhitev** [comment]
@dekatotoro Hello! Thank you! I merged from your last commit!

**Comment by dekatotoro** [comment]
@alexsanderkhitev 
Please except the xcuserdata / under the file.

**Comment by alexsanderkhitev** [comment]
@dekatotoro 
I removed xcuserdata from my source control

**Comment by Pluto-Y** [comment]
@alexsanderkhitev 
There are still two xcuserdatas you had commit, please remove it.

**Comment by alexsanderkhitev** [comment]
@Pluto-Y thank you for your help. I din't know about it!

**Comment by dekatotoro** [comment]
@alexsanderkhitev @Pluto-Y 
Thanks!

**Pull request merged**
