### PR TITLE
add support for status bar change

### PR DESCRIPTION
**Pull request by CodeEagle**
add support for status bar change

### CODE REVIEW

**Comment by dekatotoro** [comment]
How about I think that there is no need Since get in `slideMenuController?.mainViewController?.prefersStatusBarHidden()`.

**Comment by ollieatkinson** [comment]
@dekatotoro I would like a way to define the status bar style - currently the library does not allow for the changing of the colour?

**Comment by CodeEagle** [comment]
yeah, I think it unnecessary to merge this pr.
Subclass it and do the support

**Comment by osrl** [comment]
+1 with @ollieatkinson

**Pull request closed without merging**
