### PR TITLE
Added delegate methods

### PR DESCRIPTION
**Pull request by osrl**
I've added delegate methods but they are not well tested. Let me know if there is anything to fix

### CODE REVIEW

**Comment by dekatotoro** [comment]
@osrl 
Thank you pull request !

There are three pointed out.
* It will be a good to call the willOpen in UIGestureRecognizerState.Began when open in a gesture.
* It will be a good to call in openLeft or openRight when the open due to the toggle.
* Delegate should be to weak.

**Comment by osrl** [comment]
Ok I will update the pull request

**Comment by osrl** [comment]
About the second point: Toggle methods eventually calls withVelocity methods. I've already added delegate methods to the withVelocity methods.

**Comment by dekatotoro** [comment]
Since openLeftWithVelocity is also called from the gesture, it will be called delegate twice.
It is difficult If you do not make change.

**Comment by osrl** [comment]
Oh, You say that I need to remove the calls from withVelocity methods, OK. Sorry for the misunderstanding.

**Comment by dekatotoro** [comment]
To close since the correspondence in this commit.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/8e37ba2d17e8d22b2d38d2e0e868a51b5ae6f724

**Pull request closed without merging**
