### PR TITLE
Fix - status bar remains hidden occationally

### PR DESCRIPTION
**Pull request by sydneyitguy**
https://github.com/dekatotoro/SlideMenuControllerSwift/blob/master/Source/SlideMenuController.swift#L463

```
case UIGestureRecognizerState.Ended, UIGestureRecognizerState.Cancelled:
            if RightPanState.lastState != .Changed {
                return
            }
```

When this condition occurs, it just returns without `setCloseWindowLevel()`
and the status bar remains hidden even though the side bar is closed.

You can reproduce the issue by dragging the sidebar very shortly (and short distance) and release it straight away. (Menu controller - viewWillAppear is called, but `RightPanState.lastState != .Changed` is true)

Removing the conditions from L465-L464 fixed the issue for me.
I'm not sure if it affects on somewhere else.

### CODE REVIEW

**Comment by dekatotoro** [comment]
It cannot reappear, is this case state begin?

**Comment by sydneyitguy** [comment]
Do you mean you cannot reproduce the issue?

**Comment by gbitaudeau** [comment]
I can reproduce and the correction seams to be fine

**Comment by dekatotoro** [comment]
@sydneyitguy @gbitaudeau 
I am not able to reproduce this issue, but fix is I think OK!
I will merge.

**Comment by sydneyitguy** [comment]
👍

**Pull request merged**
