### PR TITLE
Add animation to change mainViewController

### PR DESCRIPTION
**Pull request by rcobelli**
This pull request adds a new method `slideMainViewController`. This allows you to change the `mainViewController` with an animation to either slide to the left or right. 

The method is `slideMainViewController(mainViewController: UIViewController, close: Bool, direction: SlideDirection, duration: Double)`

### CODE REVIEW

**Comment by Codeido** [comment]
I've cloned your fork.

Is this what you've developed?
alt text

Is this method an alternative to changeMainViewController?

**Comment by rcobelli** [comment]
Yes, that's it. I primarily intended it to be used to switch
ViewControllers when you aren't using the slide out menu (for example the
bell in the GIF below could bring you to the GO page). Before this fork, it
would just flash you to that other view controller with no animation. I
would still recommend using the changeMainViewController when you are
changing from the SlideOutMenu though.

**Comment by Codeido** [comment]
mmm i think that I do not need to put this type of customization in a library, because the animation is not very pretty, but it's just my opinion.

//cc other supporters: What do you think about that @dekatotoro @Pluto-Y @Ridwy @tasanobu @nghialv?

**Comment by rcobelli** [comment]
I made a different animation. No clue if this one is any better, figured I might as well give it one last try ¯\_(ツ)_/¯

recording

**Comment by dekatotoro** [comment]
It is interesting, but I think that it is not necessary. 
As for the person who wants to do it, should override do changeMainViewController ...

**Pull request closed without merging**
